import { jost } from '@/styles/fonts'
import './globals.css'
import type { Metadata } from 'next'
import logo from '@/public/logo/logo.ico'
import Head from 'next/head'
// import Error from "./error";

export const metadata: Metadata = {
  title: 'Beet AI',
  description: 'Generated by create next app',
  icons: logo.src,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${jost.className} text-primary-black overflow-x-hidden`}
      >
        {/* <ErrorBoundary fallback={<Error />} /> */}
        {children}
      </body>
    </html>
  )
}
